apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-testmercadolibre
  labels:
    app: ms-testmercadolibre
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ms-testmercadolibre
  template:
    metadata:
      labels:
        app: ms-testmercadolibre
    spec:
      containers:
        - name: ms-testmercadolibre
          image: build/libs/ms_testmercadolibre:0.0.1-snapshot
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          resources:
            #solicitud de memoria
            requests:
              memory: "256Mi"
              cpu: "250m"
            #limite de memoria
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-testmercadolibre
spec:
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-testmercadolibre